services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: $PROJECT_NAME$_app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    user: "1000:1000"
    depends_on:
      - mysql
      - redis
    networks:
      - $PROJECT_NAME$

  nginx:
    image: nginx:alpine
    container_name: $PROJECT_NAME$_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - $PROJECT_NAME$

  mysql:
    image: mysql:8.0
    container_name: $PROJECT_NAME$_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $PROJECT_NAME$
      MYSQL_USER: $PROJECT_NAME$
      MYSQL_PASSWORD: $PROJECT_NAME$pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - $PROJECT_NAME$

  redis:
    image: redis:alpine
    container_name: $PROJECT_NAME$_redis
    ports:
      - "6379:6379"
    networks:
      - $PROJECT_NAME$

volumes:
  mysql_data:

networks:
  $PROJECT_NAME$: